change-template: '- $TITLE ([#$NUMBER]($URL)) [@$AUTHOR]($AUTHOR_URL)'
template: |
  ## What’s Changed

  $CHANGES
  
  ## Contributors
  
  $CONTRIBUTORS
  
  **Full Changelog**: [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)